version: '3'
services:
    server1:
        build:
            context: .
        image: mariadb-es
        hostname: mariadb1
        container_name: mariadb1
        privileged: true
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'Y'
        ports:
            - 3301:3306
        networks:
            static-network:
                ipv4_address: 172.20.0.2
        volumes:
            - ./init:/tmp/init
            - ./conf/mariadb1.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
        mem_limit: 2G
    server2:
        build:
            context: .
        image: mariadb-es
        hostname: mariadb2
        container_name: mariadb2
        privileged: true
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'Y'
        ports:
            - 3302:3306
        networks:
            static-network:
                ipv4_address: 172.20.0.3
        volumes:
            - ./init:/tmp/init
            - ./conf/mariadb2.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
        depends_on:
            - server1
        mem_limit: 2G
        
    server3:
        build:
            context: .
        image: mariadb-es
        hostname: mariadb3
        container_name: mariadb3
        privileged: true
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'Y'
        ports:
            - 3303:3306
        networks:
            static-network:
                ipv4_address: 172.20.0.4
        volumes:
            - ./init:/tmp/init
            - ./conf/mariadb3.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
        depends_on:
            - server1
        mem_limit: 2G
                        
    maxs1:
        hostname: max1
        container_name: max1
        image: mariadb/maxscale
        privileged: true
        ports:
            - 4601:4006
            - 4701:4007
            - 8981:8989
        volumes:
            - maxscale:/var/lib/maxscale
            - ./conf/max.cnf:/etc/maxscale.cnf
            - ./conf/filter.json:/var/lib/maxscale/filter.json
            - ./conf/firewall.rule:/var/lib/maxscale/firewall.rule
        links:
            - "server1"
            - "server2"
            - "server3"
        mem_limit: 256M
        networks:
            static-network:
                ipv4_address: 172.20.0.5   
    maxs2:
        hostname: max2
        container_name: max2
        image: mariadb/maxscale
        privileged: true
        ports:
            - 4602:4006
            - 4702:4007
            - 8982:8989
        cap_add:
            - SYS_ADMIN
        security_opt:
            - seccomp:unconfined
        tmpfs:
            - /tmp
        volumes:
            - maxscale:/var/lib/maxscale
            - ./conf/max.cnf:/etc/maxscale.cnf
            - ./conf/filter.json:/var/lib/maxscale/filter.json
            - ./conf/firewall.rule:/var/lib/maxscale/firewall.rule
        networks:
            static-network:
                ipv4_address: 172.20.0.6
        depends_on:
            - server1
            - server2
            - server3
networks:
    static-network:
        name: static-network
        ipam:
            config:
                - subnet: 172.20.0.0/16
                  ip_range: 172.20.5.0/24
                  gateway: 172.20.5.254
volumes:
    maxscale:
