version: '3.8'

services:
    server1:
        image: mariadb/server
        container_name: mariadb1
        environment:
            - MARIADB_ROOT_PASSWORD=password
        ports:
            - 3301:3306
        networks:
            - mariadb_nw
        volumes:
            - ./init/server1:/tmp/init

    server2:
        image: mariadb/server
        container_name: mariadb2
        environment:
            - MARIADB_ROOT_PASSWORD=password
        ports:
            - 3302:3306
        networks:
            - mariadb_nw
        volumes:
            - ./init/others:/tmp/init
        depends_on:
            - server1
        
    server3:
        image: mariadb/server
        container_name: mariadb3
        environment:
            - MARIADB_ROOT_PASSWORD=password
        ports:
            - 3303:3306
        networks:
            - mariadb_nw
        volumes:
            - ./init/others:/tmp/init
        depends_on:
            - server2
                        
    maxs1:
        container_name: max1
        image: mariadb/maxscale
        ports:
            - 4401:4406
            - 6601:3306
            - 8901:8989
        networks:
            - mariadb_nw
        depends_on:
            - server1
            - server2
            - server3
            
    maxs2:
        container_name: max2
        image: mariadb/maxscale
        ports:
            - 4402:4406
            - 6602:3306
            - 8902:8989
        networks:
            - mariadb_nw
        depends_on:
            - server1
            - server2
            - server3

networks:
    mariadb_nw:
        driver: bridge