version: '3'

services:

  db1:
    build:
      context: .
      args:
        TOKEN: ${MARIADB_ENTERPRISE_TOKEN}
    image: ${IMAGE_NAME}
    hostname: ${DB1}
    container_name: ${DB1}
    env_file:
      - .env
    depends_on:
      - "db3"
    links:
      - "db2"
      - "db3"
    ports:
      - 3307:3306
    volumes:
      - ./conf:/etc/my.cnf.d
    mem_limit: ${SERVER_RAM}

  db2:
    build:
      context: .
      args:
        TOKEN: ${MARIADB_ENTERPRISE_TOKEN}
    image: ${IMAGE_NAME}
    hostname: ${DB2}
    container_name: ${DB2}
    env_file:
      - .env
    depends_on:
      - "db3"
    links:
      - "db3"
    ports:
      - 3308:3306
    volumes:
      - ./conf:/etc/my.cnf.d
    mem_limit: ${SERVER_RAM}

  db3:
    build:
      context: .
      args:
        TOKEN: ${MARIADB_ENTERPRISE_TOKEN}
    image: ${IMAGE_NAME}
    hostname: ${DB3}
    container_name: ${DB3}
    env_file:
      - .env
    ports:
      - 3309:3306
    volumes:
      - ./conf:/etc/my.cnf.d
    mem_limit: ${SERVER_RAM}

  mx1:
    image: mariadb/maxscale
    hostname: ${MX1}
    container_name: ${MX1}
    volumes:
      - maxscale:/var/lib/maxscale
    depends_on:
      - "db1"
      - "db2"
      - "db3"
    env_file:
      - .env
    links:
      - "db1"
      - "db2"
      - "db3"
    ports:
      - 3310:3306
      - 8988:8989
    mem_limit: ${MAXSCALE_RAM}

  mx2:
    image: mariadb/maxscale
    hostname: ${MX2}
    container_name: ${MX2}
    volumes:
      - maxscale:/var/lib/maxscale
    depends_on:
      - "db1"
      - "db2"
      - "db3"
    env_file:
      - .env
    links:
      - "db1"
      - "db2"
      - "db3"
    ports:
      - 3311:3306
      - 8989:8989
    mem_limit: ${MAXSCALE_RAM}

volumes:
  maxscale:
